name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # Azure VM에서 실행

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login actionimage.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t actionimage.azurecr.io/my-sample-app:latest .
          docker push actionimage.azurecr.io/my-sample-app:latest

      - name: Logout from ACR
        run: docker logout actionimage.azurecr.io
